Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2018-04, with the labels that each got.

#261 Markt Blumen Dahlmann
  cities/münster.json
Labels: City: Münster, Content

#262 Update markets for Berlin (published 09.04.2018).
  cities/berlin.json
  preprocessing/README.md
  preprocessing/berlin/raw/markets-berlin.json
Labels: City: Berlin, Content, Documentation

#263 Remove GitHub CNAME file.
  CNAME
Labels: Deployment, Project setup, Webserver

#264 Update product name for Piwik/Matomo.
  impressum.html
Labels: Documentation, Legal

#256 Update leaflet to 1.3.1
  lib/leaflet/images/layers-2x.png
  lib/leaflet/images/layers.png
  lib/leaflet/images/marker-icon-2x.png
  lib/leaflet/images/marker-icon.png
  lib/leaflet/images/marker-shadow.png
  lib/leaflet/leaflet.css
  lib/leaflet/leaflet.js
Labels: Project setup
