Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2018-05, with the labels that each got.

#266 Add Basel Market Data
  README.md
  cities/basel.json
  cities/cities.json
Labels: City: Basel, Content

#265 Remove project authors and data source.
  index.html
  js/main.js
Labels: Design, Enhancement, Mobile, Usability

#268 Remove Gemnasium badge. RIP!
  README.md
Labels: Project setup
