Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2018-12, with the labels that each got.

#273 GDPR compliance
  css/main.css
  impressum-datenschutz.html
  impressum.html.disabled
  index.html
  index.html.disabled
  info.html
  js/main.js
Labels: Legal, Severity: ★★★

#274 Update markets for Berlin (published 14.08.2018).
  cities/berlin.json
  preprocessing/berlin/raw/markets-berlin.json
Labels: City: Berlin, Content

#272 Add today marker irrespective of opening hours
  js/main.js
Labels: Bug fix, Usability
