Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2019-08, with the labels that each got.

#302 Update market data for Cottbus
  cities/cottbus.json
Labels: City: Cottbus, Content

#304 use isoweek for opening times computation
  js/main.js
Labels: Bug fix, Usability

#293 Sort Markets by Title
  cities/berlin.json
  preprocessing/berlin/compile-berlin-geojson.js
  preprocessing/berlin/raw/markets-berlin.json
Labels: Enhancement
