Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2021-07, with the labels that each got.

#376 Update screenshot shown in the README.md.
  gfx/website-karlsruhe-screenshot.jpg
Labels: Documentation

#380 Ensure marker popups work in Safari again
  js/main.js
Labels: Bug fix, Safari

#378 Update dependencies.
  package-lock.json
Labels: Project setup

#381 Update Travis CI badge.
  README.md
Labels: Project setup

#383 Update markets for Berlin (published 29.07.2021).
  cities/berlin.json
  preprocessing/berlin/raw/markets-berlin.json
Labels: City: Berlin, Content
