Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2021-03, with the labels that each got.

#354 Update markets for Berlin (published 10.03.2021).
  cities/berlin.json
  preprocessing/berlin/raw/markets-berlin.json
Labels: City: Berlin, Content

#355 Update to fabric version 2 for deployments
  .travis.yml
  deploy.sh
  fabfile.py
  requirements.txt
Labels: Deployment, Project setup

#356 Update date to match updated date of the website.
  cities/berlin.json
Labels: City: Berlin, Content

#357 Update fabfile.py to python3 + add pylint
  .travis.yml
  fabfile.py
  requirements.txt
Labels: Deployment, Project setup

#358 Let Travis CI check the shell script via shellcheck.
  .travis.yml
  deploy.sh
Labels: Project setup, Validation
