Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2021-09, with the labels that each got.

#390 Update Gelsenkirchen.
  cities/gelsenkirchen.json
  validation/markets-validator.js
Labels: Content, Validation, City: Gelsenkirchen

#391 Update dependencies.
  package-lock.json
Labels: Project setup

#393 Remove accidentally commited `.pyc` file
  fabfile.pyc
Labels: Housekeeping

#392 Enable Dependabot.
  .github/dependabot.yml
Labels: Project setup
