Repository wo-ist-markt/wo-ist-markt.github.io, pull requests merged in 2025-03, with the labels that each got.

#697 Update data source urls (München, Usingen).
  README.md
  cities/münchen.json
  cities/usingen.json
Labels: Content, City: München, City: Usingen

#698 Handle SSL verification issue due to incomplete certificate chain.
  validation/markets-validator.js
Labels: Content, City: München, Validation

#699 Add weekly farmers market in Donaueschingen
  README.md
  cities/cities.json
  cities/donaueschingen.json
Labels: Content

#700 Update markets for Berlin (published 27.02.2025).
  cities/berlin.json
  preprocessing/berlin/raw/markets-berlin.json
Labels: City: Berlin, Content

#705 Replace jasmine with node test
  package-lock.json
  package.json
  spec/citylist-spec.js
  spec/citylist.test.js
Labels: Testing, Project setup

#703 Replace rollup-plugin-css-bundle:1.0.4 with rollup-plugin-css-only:4.5.2.
  css/main.css
  js/main.js
  package-lock.json
  package.json
  rollup.config.js
Labels: Project setup

#702 Migrate from rollup 2 to rollup 3.
  package-lock.json
  package.json
  rollup.config.js
Labels: Project setup, Housekeeping
